3scale-qe/3scale-api-python

tests/integration/conftest.py, tests/integration/test_integration_application_plan.py, threescale/defaults.py, threescale/resources.py
Added integration tests for application plans.
=> Application plans integration  tests

tests/integration/conftest.py, tests/integration/test_integration_application.py
Integration tests for the application.
=> Integration test for application

tests/integration/asserts.py, tests/integration/common.py, tests/integration/conftest.py, tests/integration/test_integration_mapping_rules.py, tests/integration/test_integration_methods.py, tests/integration/test_integration_metrics.py, threescale/client.py, threescale/resources.py, threescale/utils.py
=> Add Methods, Metrics and MappingRules integration tests

Pipfile, Pipfile.lock, tests/integration/common.py, tests/integration/conftest.py, tests/integration/test_integration_metrics.py
JBOSS Issue: [https://issues.jboss.org/browse/THREESCALE-2752](https://issues.jboss.org/browse/THREESCALE-2752)
=> Differentiate limit exceeded vs disabled metric 

threescale_api/resources.py
To fix few failing proxy relevant tests ProxyConfigs and ProxyCOnfig
classes had to be updated to reflect expected behavior defined by the
tests.
=> Update behavior of access to proxy config[s]

threescale_api/resources.py
Getters for application keys and service to which application is bound.
=> New properties to resources.Application

threescale_api/resources.py
Surprisignly it didn't seem to harm.
=> Fix typo :'(

tests/integration/test_integration_policies.py, threescale_api/resources.py
Added policies.append and policies.insert
=> policies.append and policies.insert

threescale_api/resources.py
verify: bool added to method arguments
=> Application.test_request should have option for SSL verification

threescale_api/auth.py
The way how app_id+HTTP-auth works required also change in credentials.
=> Fix app_id/app_key Basic HTTP auth

threescale_api/resources.py
=> Policies.append should take *policies instead on one policy

.circleci/config.yml, .flake8, Pipfile, Pipfile.lock, README.md, tests/test_3scale_api_client.py, tests/test_rest_api_client.py, threescale_api/__init__.py, threescale_api/auth.py, threescale_api/client.py, threescale_api/resources.py, threescale_api/utils.py
Fixes:
- flake8 violations
Adds:
- circleci config
=> Add Circle CI job, fix flake8

tests/integration/test_integration_api_client.py, threescale_api/resources.py
* Add the ability to change api_client for each application.
=> Make application api_client pluggable

tests/integration/test_integration_api_client.py
Test for pluggable api_client was broken.
=> Fix api_client test

tests/integration/conftest.py, tests/integration/test_integration_custom_tenant.py, threescale_api/client.py, threescale_api/resources.py
Fixed the tenants url to /master/api/providers
Added the entity_id param to Tenant resource, so the delete would work correctly
=> modified the api so the creation of custom tennant will work

tests/integration/test_integration_activedocs.py, threescale_api/resources.py
=> add fix fetching active docs because of missing endpoint

tests/integration/conftest.py, tests/integration/test_integration_webhook.py, threescale_api/client.py, threescale_api/resources.py
@jsmadis @mganisin please review
=> Add features for webhook and webhook tests

tests/integration/test_integration_services.py, threescale_api/resources.py
@mganisin @jsmadis  please review
=> Add bugfix for getting length of proxy config list

tests/integration/conftest.py, tests/integration/test_integration_default_client.py, threescale_api/resources.py
Some entities doesn't have properly set entity_e hencenam read_by_name doesn't work on all entites.
@jsmadis @mganisin  please review
=> Add read by name workaround

tests/integration/test_integration_api_client.py, threescale_api/resources.py, threescale_api/utils.py
=> Api client changes

threescale_api/resources.py
This should allow to change state of the individual users (e.g. activate them).
Signed-off-by: Matej Dujava <mdujava@redhat.com>
=> Fix baseclass of AccountUsers

threescale_api/resources.py
* Fix wrong endpoint for `Invoices.charge()`
* Change `InvoiceState` names to be UPPERCASE
* Remove unnecessary `**kwargs` from `charge` and `state_change` methods
=> Fix Invoices

threescale_api/client.py, threescale_api/resources.py
@pehala @jsmolar @mganisin please review
=> Add auth resources for existing clients

threescale_api/resources.py
This PR partially fixes already merged PR https://github.com/3scale-qe/3scale-api-python/pull/106 and is a prerequisite for https://github.com/3scale-qe/3scale-tests/pull/17 .
=> Tenant Read and Creation of Tenant without Token

tests/integration/test_integration_tenant.py
Better tests for original #106
=> Better tests for tennat billing

threescale_api/client.py, threescale_api/resources.py
Move the check to ThreeScaleClient as there it is available for all
cases (e.g. when client is used without dealing with tenants).
Original wait_tenant_ready kept available.
Collected all the used checks of availability and added short sleep as
the checks are still insufficient
=> Refactor tenant readiness check

.gitignore, Pipfile, threescale_api/auth.py, threescale_api/client.py, threescale_api/defaults.py, threescale_api/resources.py, threescale_api/utils.py
This PR contains:
- changes required for CRD client
- small fixes of client. Some of them are required for CRD client too.
- fixes for some code style errors
Also question is how to specify minimal version of Python, but maybe we can consider to sync this with testsuite at least for now.
=> Crd client changes

.gitignore, threescale_api/auth.py, threescale_api/client.py, threescale_api/defaults.py, threescale_api/errors.py, threescale_api/resources.py, threescale_api/utils.py
Pylint fixes.
I haven't fixed these because they are waiting for some intern:
- C0114 (missing-module-docstring)
- C0115 (missing-class-docstring)
- C0116 (missing-function-docstring)
- C0302 (too-many-lines)
- R0913 (too-many-arguments)
- R0902 (too-many-instance-attributes)
- W0221 (arguments-differ)
Also I haven't fixed pylint issues which require qualified refactoring.
=> Pylint fixes

threescale_api/client.py, threescale_api/defaults.py, threescale_api/resources.py
=> fixes for crd client

tests/integration/conftest.py, tests/integration/test_integration_cms.py, threescale_api/resources.py
THREESCALE-9576, THREESCALE-9172, THREESCALE-9572, THREESCALE-9191
=> changes for bug fixes and enhacements

tests/integration/test_integration_cms.py
[see discussion](https://issues.redhat.com/browse/THREESCALE-9191?focusedId=22587945&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22587945)
=> add 2 tests for filters by section_id for objects which have not section_id

.github/workflows/release.yml
Fix this issue https://github.com/3scale-qe/3scale-api-python/actions/runs/8567708744/job/23480035163
=> fix branch used gh action

tests/integration/conftest.py, tests/integration/test_integration_service_plans.py, tests/integration/test_integration_service_subscriptions.py, threescale_api/resources.py
Add some resources into resources.py and the unit test for Service Subscription into test integrations
=> Adding Service Subscription and Service Plan resources and tests for Service Subscriptions
