- threescale_api/resources.py
It wasn't possible to manipulate with policy due to this missing
property.
> Policies(DefaultClient) was missing url property

- tests/integration/common.py
Commonly there's delay before created route for new service/apicast gets
really working. For couple of seconds requests to fresh endpoint return
503. There retry mechanism has to be used, here is 'native' requests
implementation
> Implement retry count in HttpClient for apicast requests

- threescale_api/auth.py
The credentials are expected little bit differently if Basic auth is used
together with user key.
This tries to solve same issue as outlined in MR #16 so it is alternative to that one
@michaeltcoelho ping
> Adjust user key Basic auth

- threescale_api/utils.py
Few modification to retry strategy; implicit retry cound increased to 4;
retry doesn't raise an exception for monitored status
> Modify retry mode in HttpClient

- threescale_api/auth.py
- threescale_api/resources.py
- threescale_api/utils.py
- Add support for manual OIDC authentication.
- Meaning user will have to add bearer token into headers manually, sadly full OIDC workflow would introduce another dependency used just for this.
- Extract adding retries to sessions into a separate method.
- Reintroduce `backoff_factor` into default `Session` object.
- Add `update` method to `OIDCConfig`.
- Move `oidc` from `Service` to `Proxy`.
> Add support for manual OIDC authentication

- threescale_api/auth.py
- threescale_api/utils.py
Recent change introduced few regressions that can break code using it.
Initialization of Auth object(s) was modified to still accept location
(if set) and session within HttpClient isn't altered if passed as arg.
> Make behavior of auth method compatible with older code

- threescale_api/resources.py
Here it is again, last PR #19 was closed by accident (I removed the branch, don't ask me how). It reflects recent conversation and @property way is followed
To avoid passing verify option to each api_client.request or test_request there's now option to change default value
> Option to change ssl verify for api_client

- tests/integration/test_integration_api_client.py
- threescale_api/resources.py
same name of function should be used for both @property as well as for
@property.setter
Added also basic test to verify functionality of api_client_verify
property.
> property setter should preserve name of property (for api_client_verify)

- threescale_api/utils.py
In case of heavy loaded 3scale (thousands services/products/backends)
4-times retry in api_client isn't enough. total count changed ot 8, this
"has" to be enough.
> api_client needs to retry more

- threescale_api/resources.py
backend_apis is paginated. As far as I am aware this is the only
paginated call at this moment, so it is implemented directly in that
class.
> Paginations for Backends (backend_apis)

- threescale_api/utils.py
HttpClient switched from Session.request to Session.send, for some
reason Session.send doesn't honor env variables, especially
REQUESTS_CA_BUNDLE. ssl verification stopped working because of that
under some configuration.
> Make ssl working in HttpClient again

- threescale_api/utils.py
Some parameters available in `kwargs` are not expected by `requests.Request` which fails when trying to instantiate it. Define all required parameters explicitly in the function's signature.
> Refactor HttpClient for working with ssl

- tests/integration/auth/test_app_key.py
- tests/integration/auth/test_app_key_authorization.py
- tests/integration/auth/test_different_app_key_name.py
- tests/integration/auth/test_different_user_key_name.py
- tests/integration/auth/test_user_key.py
- threescale_api/auth.py
* The values for the authorization names are now fetched from the proxy instead of being fixed values.
* The special handling of `authorization` for `AppIdKeyAuth` was removed because the `BaseClientAuth` does the same thing.
* Added integration tests for auth to make sure I didn't break anything.
> AppIdKeyAuth improvements

- tests/integration/conftest.py
- tests/integration/test_integration_services.py
- threescale_api/resources.py
Adds link to activedocs from service/product. These activedocs are related to service/product. There is `Wrapper` class for evaluation in time of calling function `list` in PR.
> Add activedoc for service

- threescale_api/resources.py
Since this issue https://issues.redhat.com/browse/THREESCALE-5826 is closed the workaround we used to use is unnecessary.
> Remove unnecessary workaround

- threescale_api/resources.py
Adding "json" response to update is OK because I've check all usages in the Testsuite.
Adding read is needed for checking correctness of imported services from OAS.
> add reading of oidc setup, return json instead of response from update

- threescale_api/utils.py
Now the verify is respected globally and not overridden by REQUESTS_CA_BUNDLE.
> Fix verify in HttpClient

- tests/integration/conftest.py
- tests/integration/test_integration_access_token.py
- threescale_api/client.py
- threescale_api/resources.py
create_token in PersonalAccesses will allow creation of new Personal Access Token like:
```
access_token = my_client.personal_accesses.create_token([
("name", "token_name"),
("permission", "rw"),
("scopes[]", "finance"),
("scopes[]", "account_management"),
("scopes[]", "stats"),
("scopes[]", "policy_registry")
])
```
Then  `access_token["access_token"]["value"]` contains the actual token
Signed-off-by: Matej Dujava <mdujava@redhat.com>
> Add AccessToken endpoint and properties for accessing tokens

- .github/workflows/release.yml
- setup.py
As implemented intially it made impossible/hard to install library
directly from codebase. Here is an attempt to make it possible again.
> Release version in setup.py commandline should not break setup.py

- threescale_api/resources.py
wait_tenant_ready is supposed to check availability of 3scale, secure
connection is not required.
> Don't check ssl in Tenant.wait_tenant_ready

- threescale_api/client.py
- threescale_api/defaults.py
Error 404 is the only error that can occur due to incomplete
initialization in 3scale, anything else should be ignored by backoff.
> Limit backoff on wait_for_tenant just for 404 errors.

- tests/integration/conftest.py
- tests/integration/test_integration_cms.py
- threescale_api/client.py
- threescale_api/resources.py
- threescale_api/utils.py
- add support for mixed entity names in one collection
- add CMS files, sections, pages, layouts, partials
- add related unit tests
> CMS objects support

- threescale_api/resources.py
Interface for new call plan_upgrade in Tenant.
Interface to get account directly from Tenant, not necessary to search
by name.
> plan_upgrade and access to account from Tenant

- tests/integration/test_integration_accounts.py
- tests/integration/test_integration_application.py
- tests/integration/test_integration_backend_mapping_rules.py
- tests/integration/test_integration_backend_metrics.py
- tests/integration/test_integration_backends.py
- tests/integration/test_integration_methods.py
- tests/integration/test_integration_metrics.py
- tests/integration/test_integration_services.py
- threescale_api/defaults.py
- threescale_api/resources.py
List of endpoints supporting pagination with per_page size:
- accounts 500
limits per app plan 50 - not implemented in client
application list for all services 500 - not implemented in client
- backend mapping rules 500
- backend method list 500
- backend metric 500
- backend 500
- service 500
invoice list by account 20 - not implemented by standard "list" method
- invoice list 20
- all cms endpoints 100
> add pagination and change related unit tests

- tests/integration/conftest.py
- tests/integration/test_integration_methods.py
- tests/integration/test_integration_tenant.py
- add ssl verify value from fixture
- change methods to hits as a parent
- metric cannot be deleted if it is part of deployed proxy
> fixes for 2.14 changes + bugs in tests

- Pipfile
- Pipfile.lock
- tests/integration/conftest.py
strbool is deprecated in new version of python.
> Remove python 3.11 dependencies

- tests/integration/conftest.py
- tests/integration/test_integration_account_plans.py
- tests/integration/test_integration_accounts.py
- tests/integration/test_integration_activedocs.py
- tests/integration/test_integration_application_plan.py
- tests/integration/test_integration_backend_usages.py
- threescale_api/client.py
- threescale_api/resources.py
GET /admin/api/application_plans
> extended api tests

- tests/integration/conftest.py
- tests/integration/test_integration_service_subscriptions.py
- threescale_api/resources.py
Add test for approve and change Service Subscription.
> Add tests into ServiceSubscriptions resource.
